### ISSUE TITLE
KeyError when trying to upload a manifest

### ISSUE THREAD

**Issue by gaheens** [cpreid2/gdc-rnaseq-tool#2]
Received a KeyError when trying to upload a manifest. Attached is the manifest and error message.
![key-error-rnaseq-tool](https://user-images.githubusercontent.com/2184586/36274433-c135ce34-1255-11e8-86f3-f34eb62b237e.png)
[gdc_manifest_20180214_175133.txt](https://github.com/cpreid2/gdc-rnaseq-tool/files/1728931/gdc_manifest_20180214_175133.txt)

The issue is that I had an extra file reference (VCF) in my manifest that was the wrong file type for this tool and it is also a controlled access file. May want to handle this error condition and display an error message vs. a KeyError.

**Comment by cpreid2** [comment]
@gaheens I have updated the code to resolve this error just a few moments ago.  The issue was that I didn't clean up the .gz files that were downloaded from a previous run of the tool.  So the key error was from the code looking for files downloaded previously.  You shouldn't see this error any longer.

**Comment by gaheens** [comment]
@cpreid2 I downloaded the new version of the code (dated today) but am still seeing this same error, even with the Test manifest.

**Comment by cpreid2** [comment]
@gaheens If you delete the RNA-Seq and miRNASeq folders in the same directory as the manifest it should resolve the problem for you.  

Though, I just updated the tool to move my fix to another part of the code so that this error shouldn't occur anymore and won't require you (or others ) to delete those folders so that it will work.  Try it again with the new code and let me know if it works.

**Comment by gaheens** [comment]
@cpreid2 This worked. Thanks!
